services:
  - type: web
    name: farmease-backend
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: node index.js
    autoDeploy: true

  - type: web
    name: farmease-frontend
    env: node
    rootDir: Tractor
    buildCommand: npm install && npm run build
    startCommand: npm run preview
    staticPublishPath: dist
    autoDeploy: true

